Test
Teiko19/TomApp pull request #3
Opened 2022-12-28 23:39 UTC by Teiko19

Add characters in header

2022-12-29 13:46 UTC, emibel commented on src/components/Header/Header.tsx
> +            <div className="border border-black rounded bg-black text-white">
extract this into a new component

2022-12-29 13:46 UTC, emibel commented on src/components/navBar/navBar.tsx
> +          <ul className="navbar-nav mr-auto">
iterate an array to create this list

2022-12-29 13:47 UTC, emibel commented on src/components/Header/Header.tsx
> +  }, []);
excelent

2022-12-29 13:50 UTC, emibel commented
* build has failed
* missing images in the PR description

2022-12-30 00:44 UTC, emibel commented on src/components/character-list/character-list.tsx
> +    <header className="">
remove header

2022-12-30 00:44 UTC, emibel commented on src/components/character-list/character-list.tsx
> +import styles from './Header.module.scss';
remove scss file

2022-12-30 00:45 UTC, emibel commented on src/components/navBar/navBar.tsx
> +import './navBar.module.scss'
import styles from './navBAr....'

2022-12-30 00:53 UTC, emibel commented on src/components/navBar/navBar.tsx
> +import './navBar.module.scss'
change class name

2023-01-02 15:35 UTC, emifsl commented on src/components/character-list/character.tsx
> +        <img src={character.image} className="img-responsive rounded-circle" alt="Responsive image"></img>
Use `<Image />` from `next/image`

2023-01-02 15:35 UTC, emifsl commented on src/components/character-list/character-list.tsx
> +import { API_CHARACTERS } from "../../API/constant";
import { API_CHARACTERS } from "../../api/constant";

2023-01-02 15:37 UTC, emifsl commented on src/components/navBar/navBar.module.scss
> +    background-color: black;
use SCSS  variable for this color

2023-01-02 16:42 UTC, emifsl commented on src/components/character-list/character-list.tsx
> +    <div>
you dont need this div

2023-01-03 13:51 UTC, emibel requested changes
pls fix comments

2023-01-03 19:09 UTC, emibel commented on src/components/character-list/character.tsx
> +      <div className="">
remove className is it has no classes

2023-01-03 19:11 UTC, emibel requested changes
fix comments

2023-01-03 19:11 UTC, emibel commented
Vercel — Deployment has failed

2023-01-03 21:05 UTC, emibel commented on src/components/character-list/character-list.tsx
>  import 'bootstrap/dist/css/bootstrap.css'
remove this from here...


this import applies to the entire app

2023-01-03 21:43 UTC, emibel approved these changes

2023-01-03 21:44 UTC, merged