add layout Main
Teiko19/TomApp pull request #4
Opened 2023-01-04 20:51 UTC by Teiko19

added layout main and child components
![image](https://user-images.githubusercontent.com/91704073/210647479-d4b86f9d-d68f-40f2-8a29-5e241828c076.png)

vercel build: https://tom-app-arlu-2dgdl0ubj-teiko19.vercel.app/

2023-01-04 23:07 UTC, Teiko19 commented
youtrack: https://emibel.youtrack.cloud/issue/RAM-1

2023-01-05 18:02 UTC, emibel commented on pages/index.tsx
> +      <Main className="mx-3 mt-3">
remove class names we don't need to pass valeus right now

2023-01-05 18:02 UTC, emibel commented on src/components/main/main.tsx
> +    <div className={`mb-3 mx-0 ${className}`}>
change mx-0 to mx-3

2023-01-05 18:02 UTC, emibel requested changes
pls fix comments

2023-01-07 00:09 UTC, merged